module.exports = {
  cn: {
    'HOME': '首页',
    'WINE': '红酒',
    'STORY': '故事',
    'NAME_CN': '中文',
    'NAME_EN': '英文',
    'INDEX_TITLE': '荣辉 澳大利亚',
    'INDEX_MSG': '当人们走进酒的世界时，他们会陶醉其中。',
    'INDEX_SIGN': '寻你所想',
    'TEL': '联系方式',
    'EMAIL': '邮箱',
    'ADDRESS': '地址',
    'WINE_TITLE': '红酒列表',
    'WINE_MSG': '提供世界级的红酒。',
    'STORY_TITLE': '你我的故事',
    'STORY_MSG': '提供世界级的红酒。',
    'BACK': '返回',
    'DETAILS': '查看详情'
  },
  en: {
    'HOME': 'Home',
    'WINE': 'Buy All Wines',
    'STORY': 'Our Story',
    'NAME_CN': 'Chinese',
    'NAME_EN': 'English',
    'INDEX_TITLE': 'RongHui Australia',
    'INDEX_MSG': 'Individuals are enhanced when they walk into the world of wine.',
    'INDEX_SIGN': 'FIND YOUR WINE',
    'TEL': 'TEL',
    'EMAIL': 'Email',
    'ADDRESS': 'Address',
    'WINE_TITLE': 'BUY ALL WINES',
    'WINE_MSG': 'Provide The World-class Red Wine.',
    'STORY_TITLE': 'OUR STORY',
    'STORY_MSG': 'Provide The World-class Red Wine.',
    'BACK': 'back',
    'DETAILS': 'See details'
  }
}
